#ifndef YAAT_RUNTIME_NAVIGATION_H
#define YAAT_RUNTIME_NAVIGATION_H

#define YAAT_NAV_CELL_SIZE 4
#define YAAT_NAV_GRID_WIDTH ((YAAT_BACKBUFFER_WIDTH + YAAT_NAV_CELL_SIZE - 1) / YAAT_NAV_CELL_SIZE)
#define YAAT_NAV_GRID_HEIGHT ((YAAT_PLAYFIELD_HEIGHT + YAAT_NAV_CELL_SIZE - 1) / YAAT_NAV_CELL_SIZE)
#define YAAT_NAV_GRID_CELLS (YAAT_NAV_GRID_WIDTH * YAAT_NAV_GRID_HEIGHT)
#define YAAT_MAX_PATH_WAYPOINTS YAAT_NAV_GRID_CELLS

#endif
